
#spring.application.name=config-client
#spring.cloud.config.label=master
#spring.cloud.config.profile=dev
#spring.cloud.config.uri= http://localhost:8888/
#server.port=8881
server:
  port: 8881
spring:
  application:
    name: config-client
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      profile: dev
      label: master

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
